# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "psRNebyndQtYkAMPwK/Nsw7klTv9ETSZDIvFQ+cYAday/qZNJj3Z830EBzCKpbiRpnj5TiP25quGPawxXvyA8BPTG2n9nZTZTHE5GJx/VvAI9DsuHC0G2S10a6e3IfEDIAju/8fXiihwKo8r4r90hUSrLBrrPW3i2Og/fX00t6PFfpBNR0Dz8Tg5/Ey7JCH/PGXtl+vQZg1fk+5aCHf976goGaugTOuhfCervYDHgqxkmcsHGY7ptWGmqnIfUM7Nqj4nGOBZjy48Ov+u4dSCvGhD3Mk7A/ZgxTJX1VmgSNKUDisNzddB+U8G/2NDNa3Usig6m1/DMtA3CizukbXtabWi8B4Abt+RuZZUK5hGS0naMq+txjIWesG3hn1f3/y8peqmyJ7YdUA2fSrq+D9KHsbVQmpUuCiiLStgk/DbTiElkDR9P4maVcBWG730NsXHwWbxN1dl8sI1cbUHQEVz9Cx1T5h96tBmodoDUVqvo3MwX3SUHo+mQFEe751fIhd+5FIZr6+VKrCoxFdGVDF0NyVRxwa3OX2extECegDLYrRUONVG0EcPE2VZTPsS4+QvBZrlILnPin0gil/AT0Dq7LIR84r/6A0Jicnp5jVfOrtTDZZNrNuCpZ9g/2oBSQR5m2Fcxy/yb2+hqpABIpUXi/6MkDm3uzko30UGLIRIavE="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
