travis:
  secure:
    BINSTAR_TOKEN: kEbHjiH6lyrMzTcF4UIipUpAgnRN8nCj3QA4sm1IUd0nlaS9ecZPhP0yyvycshf5maioOSzGDhrrSpc/P0Q+ch9JLOVjpIZIBDlmFJA9qmAivSYKqEDvQdDrjPuuVM0zCeF5Yyn/P26DAvgSM4vsLmEEK2g51qu0SaGHqfdBN9iusSYnYYW2RGPGqSZOnfaO4MW2biOrW4euE5gbbMOcPs3ruaoRtgFSTdE6gW24k4wGpTePHmEk7J+/51OLD261Gvm96uhMv6ZBV5u4gbqDBCaTlmUfWPwvNN18mgzhWhZRFRDNP7loPV8GvcveEVAYUXFBgJGE8uq2Fde8Pk3HsKEX3bOxJwyHjbyUlexewlg2oEVBH6pn32O7E1fvmHdj5VT5ZT1jMBrF3nEus+orlk0HLYUNVST3eGKB5Ya9MNXexyeVBGZcauxLgazA4IXIiVAM8l2kexFkxFfHRuZl3FbWMmulJqUXl4E3Jn+VMrHspP02fReKjg4BFzwDO9p4qe+tbyv1kkCGNtukhPrfVTXCUBojoctGOwksxDvl1Bgg3dZgdQd3eUV5fZF7A+gWizVRsRMlnzFrVBEO1w/BcDvxacjs82SW4Bed3rMLR3eihtK99sK162NqnZzZ9euFvY/WhSzdh5byM7chh0rXlfYCNvuTGj70+PiVeo/aduw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
