travis:
  secure:
    BINSTAR_TOKEN: psRNebyndQtYkAMPwK/Nsw7klTv9ETSZDIvFQ+cYAday/qZNJj3Z830EBzCKpbiRpnj5TiP25quGPawxXvyA8BPTG2n9nZTZTHE5GJx/VvAI9DsuHC0G2S10a6e3IfEDIAju/8fXiihwKo8r4r90hUSrLBrrPW3i2Og/fX00t6PFfpBNR0Dz8Tg5/Ey7JCH/PGXtl+vQZg1fk+5aCHf976goGaugTOuhfCervYDHgqxkmcsHGY7ptWGmqnIfUM7Nqj4nGOBZjy48Ov+u4dSCvGhD3Mk7A/ZgxTJX1VmgSNKUDisNzddB+U8G/2NDNa3Usig6m1/DMtA3CizukbXtabWi8B4Abt+RuZZUK5hGS0naMq+txjIWesG3hn1f3/y8peqmyJ7YdUA2fSrq+D9KHsbVQmpUuCiiLStgk/DbTiElkDR9P4maVcBWG730NsXHwWbxN1dl8sI1cbUHQEVz9Cx1T5h96tBmodoDUVqvo3MwX3SUHo+mQFEe751fIhd+5FIZr6+VKrCoxFdGVDF0NyVRxwa3OX2extECegDLYrRUONVG0EcPE2VZTPsS4+QvBZrlILnPin0gil/AT0Dq7LIR84r/6A0Jicnp5jVfOrtTDZZNrNuCpZ9g/2oBSQR5m2Fcxy/yb2+hqpABIpUXi/6MkDm3uzko30UGLIRIavE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
